runtime: go111

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /digest/cron
  script: auto
  login: admin
- url: /admin/.*
  script: auto
  login: admin
- url: /.*
  script: auto
  secure: always
